apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepiece-app
  labels:
    app: onepiece-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onepiece-app
  template:
    metadata:
      labels:
        app: onepiece-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: onepiece-app
          image: luckyregistry.azurecr.io/onepiece-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: onepiece-db-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onepiece-db-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onepiece-db-secret
                  key: SPRING_DATASOURCE_PASSWORD

