apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepiece-app
  labels:
    app: onepiece-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onepiece-app
  template:
    metadata:
      labels:
        app: onepiece-app
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: onepiece-app
        image: luckyregistry11.azurecr.io/onepiece-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
